#!/usr/bin/env bash
# Transfers a file from my client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

# Checking for command-line argument
#if [ "$#" -lt 3 ]; then
#  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
#  exit 1
#fi

# Assigning Arguments to variables
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Checking if the transfer was successful
if [ "$#" -lt 4 ]; then
  scp -o StrictHostKeyChecking=no "$path_to_file" "$username@$ip":~/
else
  # Disabling Strict Host Key checking
  scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
fi

# Checking if the transfer was successful
if [ $? -eq 0 ]; then
  echo "FILE TRANSFER WAS SUCCESSFUL"
else
  echo "FILE TRANSFER FAILED"
fi
